/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TitleComponent {
        "color": string;
        "size": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        "text": string;
    }
}
declare global {
    interface HTMLTitleComponentElement extends Components.TitleComponent, HTMLStencilElement {
    }
    var HTMLTitleComponentElement: {
        prototype: HTMLTitleComponentElement;
        new (): HTMLTitleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "title-component": HTMLTitleComponentElement;
    }
}
declare namespace LocalJSX {
    interface TitleComponent {
        "color"?: string;
        "size"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        "text"?: string;
    }
    interface IntrinsicElements {
        "title-component": TitleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "title-component": LocalJSX.TitleComponent & JSXBase.HTMLAttributes<HTMLTitleComponentElement>;
        }
    }
}
